name = "exar-api"
main = "src/index.ts"
compatibility_date = "2026-08-31"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "exar"
database_id = "9bd95dca-6c2f-439a-a4d7-53c44a82118b"
migrations_dir = "migrations"

[vars]
CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173,https://exar.armindashti.workers.dev"
